---
rhsm_manage: true

jboss_eap_version: 7.3
rhel_version: 7-server

rhsm_repos:
  - "rhel-7-server-rpms"
  - "jb-eap-{{ jboss_eap_version }}-for-rhel-{{ rhel_version }}-rpms"

jboss_eap_yum_group: jboss-eap7

yum_packages:
  - firewalld
  - "@{{ jboss_eap_yum_group }}"

jboss_eap_service_name: eap7-standalone

jboss_eap_service_config: standalone-ha.xml
jboss_eap_bind: 0.0.0.0

jboss_home: "/opt/rh/eap7/root/usr/share/wildfly"

deploy_apps:
  []
  # name: simple-webapp
  # url:
deploy_app_tmp_dir: /tmp

management_port: 9990
mod_cluster_port: 6666
