---

- name: Download a app to deploy - {{ app.name }}
  get_url:
    url: "{{ app.url }}"
    dest: "{{ deploy_app_tmp_dir }}"
  register: downloaded_app

- name: Build Deployment Facts
  set_fact:
    jcliff_deployments: "{{ jcliff_deployments|default([]) + [ {'name': (app.name | default(downloaded_app.dest | basename)), 'path': downloaded_app.dest} ] }}"
